import { describe, expect, it } from 'vitest'
import { HERO_NAMES_ZH } from './heroes-zh'

const STRATZ_HERO_NAMES = [
  'Anti-Mage',
  'Axe',
  'Bane',
  'Bloodseeker',
  'Crystal Maiden',
  'Drow Ranger',
  'Earthshaker',
  'Juggernaut',
  'Mirana',
  'Morphling',
  'Shadow Fiend',
  'Phantom Lancer',
  'Puck',
  'Pudge',
  'Razor',
  'Sand King',
  'Storm Spirit',
  'Sven',
  'Tiny',
  'Vengeful Spirit',
  'Windranger',
  'Zeus',
  'Kunkka',
  'Lina',
  'Lion',
  'Shadow Shaman',
  'Slardar',
  'Tidehunter',
  'Witch Doctor',
  'Lich',
  'Riki',
  'Enigma',
  'Tinker',
  'Sniper',
  'Necrophos',
  'Warlock',
  'Beastmaster',
  'Queen of Pain',
  'Venomancer',
  'Faceless Void',
  'Wraith King',
  'Death Prophet',
  'Phantom Assassin',
  'Pugna',
  'Templar Assassin',
  'Viper',
  'Luna',
  'Dragon Knight',
  'Dazzle',
  'Clockwerk',
  'Leshrac',
  "Nature's Prophet",
  'Lifestealer',
  'Dark Seer',
  'Clinkz',
  'Omniknight',
  'Enchantress',
  'Huskar',
  'Night Stalker',
  'Broodmother',
  'Bounty Hunter',
  'Weaver',
  'Jakiro',
  'Batrider',
  'Chen',
  'Spectre',
  'Ancient Apparition',
  'Doom',
  'Ursa',
  'Spirit Breaker',
  'Gyrocopter',
  'Alchemist',
  'Invoker',
  'Silencer',
  'Outworld Destroyer',
  'Lycan',
  'Brewmaster',
  'Shadow Demon',
  'Lone Druid',
  'Chaos Knight',
  'Meepo',
  'Treant Protector',
  'Ogre Magi',
  'Undying',
  'Rubick',
  'Disruptor',
  'Nyx Assassin',
  'Naga Siren',
  'Keeper of the Light',
  'Io',
  'Visage',
  'Slark',
  'Medusa',
  'Troll Warlord',
  'Centaur Warrunner',
  'Magnus',
  'Timbersaw',
  'Bristleback',
  'Tusk',
  'Skywrath Mage',
  'Abaddon',
  'Elder Titan',
  'Legion Commander',
  'Techies',
  'Ember Spirit',
  'Earth Spirit',
  'Underlord',
  'Terrorblade',
  'Phoenix',
  'Oracle',
  'Winter Wyvern',
  'Arc Warden',
  'Monkey King',
  'Dark Willow',
  'Pangolier',
  'Grimstroke',
  'Hoodwink',
  'Void Spirit',
  'Snapfire',
  'Mars',
  'Dawnbreaker',
  'Marci',
  'Primal Beast',
  'Muerta',
  'Ringmaster',
  'Kez',
  'Largo',
]

describe('HERO_NAMES_ZH', () => {
  it('covers every STRATZ hero name', () => {
    const missing = STRATZ_HERO_NAMES.filter((name) => !HERO_NAMES_ZH[name])
    expect(missing).toEqual([])
  })

  it('uses official Chinese names for well-known heroes', () => {
    expect(HERO_NAMES_ZH['Invoker']).toBe('祈求者')
    expect(HERO_NAMES_ZH['Hoodwink']).toBe('森海飞霞')
    expect(HERO_NAMES_ZH['Anti-Mage']).toBe('敌法师')
    expect(HERO_NAMES_ZH['Outworld Destroyer']).toBe('殁境神蚀者')
    expect(HERO_NAMES_ZH['Largo']).toBe('朗戈')
  })

  it('has no empty or duplicate translations', () => {
    const values = Object.values(HERO_NAMES_ZH)
    expect(values.every((v) => v.length > 0)).toBe(true)
    expect(new Set(values).size).toBe(values.length)
  })
})
